#!/bin/sh

# ./run >run.txt

./../http -u Cmdenv -f ./script.ini -c single_connection_noPipe
./../http -u Cmdenv -f ./script.ini -c multi_3_connection_noPipe
./../http -u Cmdenv -f ./script.ini -c multi_6_connection_noPipe
./../http -u Cmdenv -f ./script.ini -c multi_12_connection_noPipe
./../http -u Cmdenv -f ./script.ini -c multi_24_connection_noPipe
./../http -u Cmdenv -f ./script.ini -c single_connection_2pipe
./../http -u Cmdenv -f ./script.ini -c single_connection_4pipe
./../http -u Cmdenv -f ./script.ini -c single_connection_8pipe
./../http -u Cmdenv -f ./script.ini -c single_connection_16pipe
./../http -u Cmdenv -f ./script.ini -c single_connection_32pipe
./../http -u Cmdenv -f ./script.ini -c normal_pipe_11
./../http -u Cmdenv -f ./script.ini -c normal_pipe_12
./../http -u Cmdenv -f ./script.ini -c normal_pipe_21
./../http -u Cmdenv -f ./script.ini -c normal_pipe_22